### ISSUE TITLE
关于vocab和embed

### ISSUE THREAD

**Issue by qniguoym** [zliucr/mixed-language-training#3]
你好，可以对nlu_emb的各个文件做下说明吗，比如使用的什么样的embedding，感谢~

**Comment by zliucr** [comment]
你好，
名字里带有mix的embedding里含有target language keywords，是用于mixed language training；
名字里带有attn的表示keywords是使用attention layer挑选的；
名字里带有manu表示keywords是manually挑选的；
名字里带有clean的是用于使用delexicalization。

**Comment by qniguoym** [comment]
感谢~ 这些embedding使用的是什么方法得到的呢？

**Comment by zliucr** [comment]
Embedding使用的是RCSLS embeddings (https://fasttext.cc/docs/en/aligned-vectors.html)
